create table databasechangelog
(
    id            varchar(255) not null,
    author        varchar(255) not null,
    filename      varchar(255) not null,
    dateexecuted  timestamp    not null,
    orderexecuted integer      not null,
    exectype      varchar(10)  not null,
    md5sum        varchar(35),
    description   varchar(255),
    comments      varchar(255),
    tag           varchar(255),
    liquibase     varchar(20),
    contexts      varchar(255),
    labels        varchar(255),
    deployment_id varchar(10)
);

alter table databasechangelog
    owner to "shareholder-register";

grant delete, insert, select, update on databasechangelog to phoen_modify;

grant select on databasechangelog to phoen_read;

create table databasechangeloglock
(
    id          integer not null
        primary key,
    locked      boolean not null,
    lockgranted timestamp,
    lockedby    varchar(255)
);

alter table databasechangeloglock
    owner to "shareholder-register";

grant delete, insert, select, update on databasechangeloglock to phoen_modify;

grant select on databasechangeloglock to phoen_read;

create table address
(
    id        bigint generated by default as identity
        primary key,
    line1     varchar(70),
    line2     varchar(70),
    post_code varchar(16),
    city      varchar(70),
    country   varchar(2)
);

alter table address
    owner to "shareholder-register";

grant select, usage on sequence address_id_seq to phoen_modify;

grant select, usage on sequence address_id_seq to phoen_read;

grant delete, insert, select, update on address to phoen_modify;

grant select on address to phoen_read;

create table issuer
(
    id                            bigint generated by default as identity
        primary key,
    name                          varchar(255) not null,
    source                        varchar(10)  not null,
    ident                         varchar(35)  not null
        constraint unique_ident
            unique,
    address_id                    bigint
        constraint fk_address_issuer
            references address,
    note                          varchar(1000),
    issuer_type                   varchar(255),
    residence_country             varchar(2),
    vat_number                    varchar(255),
    last_csd_update               timestamp,
    issuer_lei                    varchar(255),
    organization_type             varchar(255),
    agreement_status              varchar(255),
    issuer_status                 boolean,
    tax_number                    varchar(255),
    email                         varchar(255),
    max_vote_int                  numeric,
    max_vote_pct                  numeric,
    max_vote_special              boolean,
    co_address                    varchar(255),
    change_of_agreement           date,
    global_paper_quantity_account varchar(255),
    post_address_id               bigint
        constraint fk_shareholder_post_address_id
            references address
);

alter table issuer
    owner to "shareholder-register";

grant select, usage on sequence issuer_id_seq to phoen_modify;

grant select, usage on sequence issuer_id_seq to phoen_read;

grant delete, insert, select, update on issuer to phoen_modify;

grant select on issuer to phoen_read;

create table issuer_property
(
    issuer_id      bigint       not null
        constraint fk_issuer_issuer_property
            references issuer,
    property       varchar(35)  not null,
    property_value varchar(255) not null,
    last_changed   timestamp,
    source         varchar(10),
    primary key (issuer_id, property)
);

alter table issuer_property
    owner to "shareholder-register";

grant delete, insert, select, update on issuer_property to phoen_modify;

grant select on issuer_property to phoen_read;

create table instrument
(
    id                              bigint generated by default as identity
        primary key,
    isin                            varchar(12) not null
        constraint unique_instrument_isin
            unique,
    issuer_id                       bigint
        constraint fk_issuer_instrument
            references issuer,
    name                            varchar(255),
    instrument_type                 varchar(35),
    status                          varchar(35),
    currency                        varchar(3),
    own_shares                      bigint,
    shares_issued                   bigint,
    issued_capital                  numeric(31, 13),
    nominal_value_per_share         numeric(31, 13),
    votes_per_share                 bigint,
    cfi                             varchar(35),
    last_static_update              date,
    source                          varchar(10),
    allow_update                    boolean default true,
    security_form                   varchar(35),
    share_class                     varchar(35),
    last_operation_on_isin          varchar(255),
    part_of_capital                 boolean,
    materialized_shares             numeric,
    dematerialized_shares           numeric,
    registration_country            varchar(255),
    issuer_lei                      varchar(255),
    issuer_agent                    varchar(255),
    issuer_agent_name               varchar(255),
    face_value                      numeric,
    total_capital_registered        numeric,
    registration_date               date,
    transfer_restrictions           varchar(255),
    payment_status                  varchar(255),
    form                            varchar(255),
    pledging                        boolean,
    norwegian_owners                integer,
    non_norwegian_owners            integer,
    marketplace                     varchar(255),
    ticker                          varchar(255),
    ask                             boolean,
    total_capital_registered_in_vps boolean,
    total_capital_in_vps            numeric,
    instrument_sub_type             varchar(255),
    multiple_vote_register_shares   numeric,
    voting_right                    varchar(255),
    depositary_receipt              varchar(255),
    share_capital_registered        numeric(31, 13)
);

alter table instrument
    owner to "shareholder-register";

grant select, usage on sequence instrument_id_seq to phoen_modify;

grant select, usage on sequence instrument_id_seq to phoen_read;

grant delete, insert, select, update on instrument to phoen_modify;

grant select on instrument to phoen_read;

create table instrument_property
(
    instrument_id  bigint       not null
        constraint fk_instrument_instrument_property
            references instrument,
    property       varchar(35)  not null,
    property_value varchar(255) not null,
    last_changed   timestamp,
    source         varchar(10),
    primary key (instrument_id, property)
);

alter table instrument_property
    owner to "shareholder-register";

grant delete, insert, select, update on instrument_property to phoen_modify;

grant select on instrument_property to phoen_read;

create table error_message
(
    id         bigint generated by default as identity
        primary key,
    error_code varchar(255) not null,
    language   varchar(16)  not null,
    message    varchar      not null,
    constraint unique_error_message_error_code_language
        unique (error_code, language)
);

alter table error_message
    owner to "shareholder-register";

grant select, usage on sequence error_message_id_seq to phoen_modify;

grant select, usage on sequence error_message_id_seq to phoen_read;

grant delete, insert, select, update on error_message to phoen_modify;

grant select on error_message to phoen_read;

create table revinfo
(
    rev      bigint generated by default as identity
        primary key,
    revtstmp timestamp    not null,
    username varchar(255) not null
);

alter table revinfo
    owner to "shareholder-register";

grant select, usage on sequence revinfo_rev_seq to phoen_modify;

grant select, usage on sequence revinfo_rev_seq to phoen_read;

grant delete, insert, select, update on revinfo to phoen_modify;

grant select on revinfo to phoen_read;

create table issuer_aud
(
    id                            bigint   not null,
    name                          varchar(255),
    source                        varchar(10),
    ident                         varchar(35),
    address_id                    bigint,
    note                          varchar(1000),
    issuer_type                   varchar(255),
    residence_country             varchar(2),
    vat_number                    varchar(255),
    rev                           integer  not null,
    revtype                       smallint not null,
    issuer_lei                    varchar(255),
    organization_type             varchar(255),
    agreement_status              varchar(255),
    issuer_status                 boolean,
    tax_number                    varchar(255),
    email                         varchar(255),
    max_vote_int                  numeric,
    max_vote_pct                  numeric,
    max_vote_special              boolean,
    co_address                    varchar(255),
    change_of_agreement           date,
    global_paper_quantity_account varchar(255),
    post_address_id               bigint,
    primary key (id, rev)
);

alter table issuer_aud
    owner to "shareholder-register";

grant delete, insert, select, update on issuer_aud to phoen_modify;

grant select on issuer_aud to phoen_read;

create table issuer_property_aud
(
    issuer_id      bigint      not null,
    property       varchar(35) not null,
    property_value varchar(255),
    rev            integer     not null,
    revtype        smallint    not null,
    source         varchar(10),
    last_changed   timestamp,
    primary key (issuer_id, property, rev, revtype)
);

alter table issuer_property_aud
    owner to "shareholder-register";

grant delete, insert, select, update on issuer_property_aud to phoen_modify;

grant select on issuer_property_aud to phoen_read;

create table address_aud
(
    id        bigint   not null,
    line1     varchar(70),
    line2     varchar(70),
    post_code varchar(16),
    city      varchar(70),
    country   varchar(2),
    rev       integer  not null,
    revtype   smallint not null,
    primary key (id, rev)
);

alter table address_aud
    owner to "shareholder-register";

grant delete, insert, select, update on address_aud to phoen_modify;

grant select on address_aud to phoen_read;

create table instrument_aud
(
    id                              bigint   not null,
    isin                            varchar(12),
    issuer_id                       bigint,
    name                            varchar(255),
    instrument_type                 varchar(35),
    status                          varchar(35),
    currency                        varchar(3),
    own_shares                      bigint,
    shares_issued                   bigint,
    issued_capital                  numeric(31, 13),
    nominal_value_per_share         numeric(31, 13),
    votes_per_share                 bigint,
    cfi                             varchar(35),
    last_static_update              date,
    source                          varchar(10),
    allow_update                    boolean,
    rev                             integer  not null,
    revtype                         smallint not null,
    security_form                   varchar(35),
    share_class                     varchar(35),
    last_operation_on_isin          varchar(255),
    part_of_capital                 boolean,
    materialized_shares             numeric,
    dematerialized_shares           numeric,
    registration_country            varchar(255),
    issuer_lei                      varchar(255),
    issuer_agent                    varchar(255),
    issuer_agent_name               varchar(255),
    face_value                      numeric,
    total_capital_registered        numeric,
    registration_date               date,
    transfer_restrictions           varchar(255),
    payment_status                  varchar(255),
    form                            varchar(255),
    pledging                        boolean,
    norwegian_owners                integer,
    non_norwegian_owners            integer,
    marketplace                     varchar(255),
    ticker                          varchar(255),
    ask                             boolean,
    total_capital_registered_in_vps boolean,
    total_capital_in_vps            numeric,
    instrument_sub_type             varchar(255),
    multiple_vote_register_shares   numeric,
    voting_right                    varchar(255),
    depositary_receipt              varchar(255),
    share_capital_registered        numeric(31, 13),
    primary key (id, rev)
);

alter table instrument_aud
    owner to "shareholder-register";

grant delete, insert, select, update on instrument_aud to phoen_modify;

grant select on instrument_aud to phoen_read;

create table instrument_property_aud
(
    instrument_id  bigint      not null,
    property       varchar(35) not null,
    property_value varchar(255),
    rev            integer     not null,
    revtype        smallint    not null,
    source         varchar(10),
    last_changed   timestamp,
    primary key (instrument_id, property, rev, revtype)
);

alter table instrument_property_aud
    owner to "shareholder-register";

grant delete, insert, select, update on instrument_property_aud to phoen_modify;

grant select on instrument_property_aud to phoen_read;

create table shareholder_aud
(
    id                         bigint   not null,
    shareholder_unique_id      varchar(255),
    name                       varchar,
    shareholder_type           varchar(255),
    investor_id                varchar(255),
    reference_date             date,
    email                      varchar(255),
    address_id                 bigint,
    co_address_id              bigint,
    address_2_id               bigint,
    issuer_id                  bigint,
    rev                        integer  not null,
    revtype                    smallint not null,
    source                     varchar(10),
    phone_number               varchar(12),
    note                       varchar(1000),
    foreign_shareholder        boolean,
    corporate_action_id        bigint,
    shareholder_id_type        varchar(255),
    citizenship                varchar(255),
    electronic_communication   varchar(255),
    date_of_production         date,
    request_date               date,
    pledge                     boolean,
    status                     varchar(255),
    date_of_birth              date,
    municipality_of_birth      varchar(255),
    nationality                varchar(255),
    legal_representative       varchar(255),
    legal_representative_email varchar(255),
    residential_address        varchar(255),
    residential_co_address     varchar(255),
    country_of_registration    varchar(255),
    account_type               varchar(255),
    bank_account               varchar(255),
    foreign_bank_account       varchar(255),
    tax_domicile               varchar(255),
    tax_at_source              varchar(255),
    language                   varchar(255),
    percentage_of_holding      numeric,
    reason                     varchar(255),
    event_type                 varchar(255),
    coupon                     varchar(255),
    instruction_type           varchar(255),
    shareholder_co_address     varchar(255),
    residential_address_id     bigint,
    primary key (id, rev)
);

alter table shareholder_aud
    owner to "shareholder-register";

grant delete, insert, select, update on shareholder_aud to phoen_modify;

grant select on shareholder_aud to phoen_read;

create table shareholder_property_aud
(
    shareholder_id bigint      not null,
    property       varchar(35) not null,
    property_value varchar(255),
    rev            integer     not null,
    revtype        smallint    not null,
    source         varchar(10),
    last_changed   timestamp,
    primary key (shareholder_id, property, rev, revtype)
);

alter table shareholder_property_aud
    owner to "shareholder-register";

grant delete, insert, select, update on shareholder_property_aud to phoen_modify;

grant select on shareholder_property_aud to phoen_read;

create table external_user
(
    id              bigint generated by default as identity
        constraint pk_external_user_id
            primary key,
    user_identifier varchar(255) not null
        constraint unique_external_user_user_identifier
            unique,
    name            varchar(255) default 'Unknown'::character varying,
    created_by      varchar(255),
    created_ts      timestamp,
    last_changed_by varchar(255),
    last_changed_ts timestamp
);

alter table external_user
    owner to "shareholder-register";

grant select, usage on sequence external_user_id_seq to phoen_modify;

grant select, usage on sequence external_user_id_seq to phoen_read;

grant delete, insert, select, update on external_user to phoen_modify;

grant select on external_user to phoen_read;

create table issuer_external_user
(
    id               bigint generated by default as identity
        primary key,
    issuer_id        bigint not null
        constraint fk_issuer_external_user_issuer
            references issuer,
    external_user_id bigint not null
        constraint fk_issuer_external_user_external_user
            references external_user,
    created_by       varchar(255),
    created_ts       timestamp,
    last_changed_by  varchar(255),
    last_changed_ts  timestamp,
    constraint uniq_issuer_external_user_issuer_id_external_user_id
        unique (issuer_id, external_user_id)
);

alter table issuer_external_user
    owner to "shareholder-register";

grant select, usage on sequence issuer_external_user_id_seq to phoen_modify;

grant select, usage on sequence issuer_external_user_id_seq to phoen_read;

create index issuer_external_user_external_user_id_index
    on issuer_external_user (external_user_id);

grant delete, insert, select, update on issuer_external_user to phoen_modify;

grant select on issuer_external_user to phoen_read;

create table shareholder_view
(
    id                 bigint generated by default as identity
        primary key,
    name               varchar(255) not null,
    issuer_id          bigint
        constraint fk_issuer_shareholder_view
            references issuer,
    filters            varchar(5000),
    columns            varchar(2000),
    for_internal_users boolean,
    created_by         varchar(255),
    created_ts         timestamp,
    last_changed_by    varchar(255),
    last_changed_ts    timestamp
);

alter table shareholder_view
    owner to "shareholder-register";

grant select, usage on sequence shareholder_view_id_seq to phoen_modify;

grant select, usage on sequence shareholder_view_id_seq to phoen_read;

grant delete, insert, select, update on shareholder_view to phoen_modify;

grant select on shareholder_view to phoen_read;

create table custodian
(
    id           bigint generated by default as identity
        primary key,
    custodian_id varchar(255) not null
        constraint unique_custodian_custodian_id
            unique,
    name         varchar      not null
);

alter table custodian
    owner to "shareholder-register";

grant select, usage on sequence custodian_id_seq to phoen_modify;

grant select, usage on sequence custodian_id_seq to phoen_read;

grant delete, insert, select, update on custodian to phoen_modify;

grant select on custodian to phoen_read;

create table shareholder_group
(
    id         bigint generated by default as identity
        primary key,
    name       varchar(255) not null,
    issuer_id  bigint
        constraint fk_issuer_shareholder_group
            references issuer,
    note       varchar(512),
    created_by varchar(255),
    created_ts timestamp
);

alter table shareholder_group
    owner to "shareholder-register";

grant select, usage on sequence shareholder_group_id_seq to phoen_modify;

grant select, usage on sequence shareholder_group_id_seq to phoen_read;

grant delete, insert, select, update on shareholder_group to phoen_modify;

grant select on shareholder_group to phoen_read;

create table recently_worked_on_issuer
(
    id              bigint generated by default as identity
        primary key,
    issuer_id       bigint       not null
        constraint fk_recently_worked_on_issuer_issuer
            references issuer,
    user_identifier varchar(255) not null,
    created_by      varchar(255),
    created_ts      timestamp    not null
);

alter table recently_worked_on_issuer
    owner to "shareholder-register";

grant select, usage on sequence recently_worked_on_issuer_id_seq to phoen_modify;

grant select, usage on sequence recently_worked_on_issuer_id_seq to phoen_read;

create index recently_worked_on_issuer_user_identifier_index
    on recently_worked_on_issuer (user_identifier);

create index recently_worked_on_issuer_issuer_id_index
    on recently_worked_on_issuer (issuer_id);

grant delete, insert, select, update on recently_worked_on_issuer to phoen_modify;

grant select on recently_worked_on_issuer to phoen_read;

create table holding_aud
(
    id                    bigint   not null,
    isin                  varchar,
    holding_value         numeric(18, 6),
    holding_date          date,
    account_id            bigint,
    source                varchar(10),
    note                  varchar(1000),
    rev                   integer  not null,
    revtype               smallint not null,
    percentage_of_holding numeric(18, 6),
    corporate_event_id    varchar(255),
    vote_rights           varchar(255),
    abi_guarantee         varchar(255),
    not_dematerialized    boolean,
    number_certificate    varchar(255),
    not_centralized       boolean,
    primary key (id, rev)
);

alter table holding_aud
    owner to "shareholder-register";

grant delete, insert, select, update on holding_aud to phoen_modify;

grant select on holding_aud to phoen_read;

create table holding_property_aud
(
    holding_id     bigint      not null,
    property       varchar(35) not null,
    property_value varchar(255),
    source         varchar(10),
    last_changed   timestamp,
    rev            integer     not null,
    revtype        smallint    not null,
    primary key (holding_id, property, rev, revtype)
);

alter table holding_property_aud
    owner to "shareholder-register";

grant delete, insert, select, update on holding_property_aud to phoen_modify;

grant select on holding_property_aud to phoen_read;

create table issuer_subscription
(
    id              bigint generated by default as identity
        primary key,
    subscription_id varchar(255) not null
        constraint unique_issuer_subscription_subscription_id
            unique,
    issuer_id       bigint       not null
        constraint fk_issuer_subscription_issuer
            references issuer
);

alter table issuer_subscription
    owner to "shareholder-register";

grant select, usage on sequence issuer_subscription_id_seq to phoen_modify;

grant select, usage on sequence issuer_subscription_id_seq to phoen_read;

create index issuer_subscription_issuer_id_index
    on issuer_subscription (issuer_id);

grant delete, insert, select, update on issuer_subscription to phoen_modify;

grant select on issuer_subscription to phoen_read;

create table issuer_subscription_translation
(
    id                     bigint generated by default as identity
        primary key,
    language               varchar(16) not null,
    name                   varchar     not null,
    description            varchar,
    start_date             timestamp,
    end_date               timestamp,
    issuer_subscription_id bigint      not null
        constraint fk_issuer_subscription_translation_issuer_subscription
            references issuer_subscription
);

alter table issuer_subscription_translation
    owner to "shareholder-register";

grant select, usage on sequence issuer_subscription_translation_id_seq to phoen_modify;

grant select, usage on sequence issuer_subscription_translation_id_seq to phoen_read;

create index issuer_subscription_translation_issuer_subscription_id_index
    on issuer_subscription_translation (issuer_subscription_id);

grant delete, insert, select, update on issuer_subscription_translation to phoen_modify;

grant select on issuer_subscription_translation to phoen_read;

create table error_log
(
    id              bigint generated by default as identity
        primary key,
    details         varchar,
    error_case      varchar(255) not null,
    status          varchar(255) not null,
    issuer_id       bigint
        constraint fk_error_log_issuer
            references issuer,
    created_by      varchar(255),
    created_ts      timestamp    not null,
    last_changed_by varchar(255),
    last_changed_ts timestamp
);

alter table error_log
    owner to "shareholder-register";

grant select, usage on sequence error_log_id_seq to phoen_modify;

grant select, usage on sequence error_log_id_seq to phoen_read;

create index error_log_issuer_id_index
    on error_log (issuer_id);

create index error_log_created_ts_index
    on error_log (created_ts);

grant delete, insert, select, update on error_log to phoen_modify;

grant select on error_log to phoen_read;

create table corporate_action
(
    id                          bigint generated by default as identity
        primary key,
    corp_id                     varchar(255),
    record_date                 date,
    pay_date                    date,
    event_type                  varchar(255),
    instruction_deadline        timestamp,
    first_call                  timestamp,
    second_call                 timestamp,
    third_call                  timestamp,
    coupon                      integer,
    conversion_ratio            varchar(255),
    quantity                    varchar(255),
    status                      varchar(255),
    general_meeting_location_id bigint
        constraint fk_corporate_action_general_meeting_location_id
            references address
);

alter table corporate_action
    owner to "shareholder-register";

grant select, usage on sequence corporate_action_id_seq to phoen_modify;

grant select, usage on sequence corporate_action_id_seq to phoen_read;

create table shareholder
(
    id                         bigint generated by default as identity
        primary key,
    shareholder_unique_id      varchar(255) not null
        constraint unique_shareholder_unique_id
            unique,
    name                       varchar,
    shareholder_type           varchar(255),
    investor_id                varchar(255),
    reference_date             date,
    email                      varchar(255),
    address_id                 bigint
        constraint fk_address_shareholder
            references address,
    co_address_id              bigint
        constraint fk_co_address_shareholder
            references address,
    address_2_id               bigint
        constraint fk_address_2_shareholder
            references address,
    issuer_id                  bigint
        constraint fk_shareholder_issuer_id
            references issuer,
    source                     varchar(10),
    phone_number               varchar(12),
    note                       varchar(1000),
    created_ts                 timestamp    not null,
    created_by                 varchar(255) not null,
    foreign_shareholder        boolean,
    corporate_action_id        bigint
        constraint fk_shareholder_corporate_action_id
            references corporate_action,
    last_changed_ts            timestamp,
    last_changed_by            varchar(255),
    shareholder_id_type        varchar(255),
    citizenship                varchar(255),
    electronic_communication   boolean,
    date_of_production         date,
    request_date               date,
    pledge                     boolean,
    status                     varchar(255),
    date_of_birth              date,
    municipality_of_birth      varchar(255),
    nationality                varchar(255),
    legal_representative       varchar(255),
    legal_representative_email varchar(255),
    residential_address        varchar(255),
    residential_co_address     varchar(255),
    country_of_registration    varchar(255),
    account_type               varchar(255),
    bank_account               varchar(255),
    foreign_bank_account       varchar(255),
    tax_domicile               varchar(255),
    tax_at_source              varchar(255),
    language                   varchar(255),
    percentage_of_holding      numeric,
    reason                     varchar(255),
    event_type                 varchar(255),
    coupon                     varchar(255),
    instruction_type           varchar(255),
    shareholder_co_address     varchar(255),
    residential_address_id     bigint
        constraint fk_shareholder_residential_address_id
            references address,
    last_csd_update            timestamp
);

alter table shareholder
    owner to "shareholder-register";

grant select, usage on sequence shareholder_id_seq to phoen_modify;

grant select, usage on sequence shareholder_id_seq to phoen_read;

create index shareholder_issuer_id_index
    on shareholder (issuer_id);

create index shareholder_corporate_action_id_index
    on shareholder (corporate_action_id);

create index shareholder_investor_id_index
    on shareholder (investor_id);

create index shareholder_last_update_index
    on shareholder (last_csd_update);

create index idx_shareholder_issuer_id
    on shareholder (issuer_id);

grant delete, insert, select, update on shareholder to phoen_modify;

grant select on shareholder to phoen_read;

create table shareholder_property
(
    shareholder_id bigint       not null
        constraint fk_shareholder_shareholder_property
            references shareholder,
    property       varchar(35)  not null,
    property_value varchar(255) not null,
    source         varchar(10),
    last_changed   timestamp,
    primary key (shareholder_id, property)
);

alter table shareholder_property
    owner to "shareholder-register";

grant delete, insert, select, update on shareholder_property to phoen_modify;

grant select on shareholder_property to phoen_read;

create table account
(
    id               bigint generated by default as identity
        primary key,
    communication_id varchar(255),
    account_number   varchar(255),
    account_type     varchar(255),
    shareholder_id   bigint
        constraint fk_account_shareholder
            references shareholder,
    custodian_id     bigint
        constraint fk_account_custodian
            references custodian,
    source           varchar(10)
);

alter table account
    owner to "shareholder-register";

grant select, usage on sequence account_id_seq to phoen_modify;

grant select, usage on sequence account_id_seq to phoen_read;

create index account_shareholder_id_index
    on account (shareholder_id);

create index account_account_number_index
    on account (account_number);

create index account_custodian_id_index
    on account (custodian_id);

create index account_communication_id_index
    on account (communication_id);

grant delete, insert, select, update on account to phoen_modify;

grant select on account to phoen_read;

create table holding
(
    id                    bigint generated by default as identity
        primary key,
    isin                  varchar        not null
        constraint fk_holding_isin
            references instrument (isin),
    holding_value         numeric(18, 6) not null,
    holding_date          date           not null,
    account_id            bigint
        constraint fk_holding_account
            references account,
    source                varchar(10),
    created_by            varchar(255),
    created_ts            timestamp,
    note                  varchar(1000),
    last_update           timestamp,
    percentage_of_holding numeric(18, 6),
    corporate_event_id    varchar(255),
    vote_rights           varchar(255),
    abi_guarantee         varchar(255),
    not_dematerialized    boolean,
    number_certificate    varchar(255),
    not_centralized       boolean
);

alter table holding
    owner to "shareholder-register";

grant select, usage on sequence holding_id_seq to phoen_modify;

grant select, usage on sequence holding_id_seq to phoen_read;

create index holding_holding_date_index
    on holding (holding_date);

create index holding_account_id_index
    on holding (account_id);

create index holding_isin_index
    on holding (isin);

create index holding_account_id_isin_holding_date_holding_value_index
    on holding (account_id, isin, holding_date, holding_value);

create index holding_last_update_index
    on holding (last_update);

grant delete, insert, select, update on holding to phoen_modify;

grant select on holding to phoen_read;

create table holding_property
(
    holding_id     bigint       not null
        constraint fk_holding_holding_property
            references holding,
    property       varchar(35)  not null,
    property_value varchar(255) not null,
    source         varchar(10),
    last_changed   timestamp,
    primary key (holding_id, property)
);

alter table holding_property
    owner to "shareholder-register";

grant delete, insert, select, update on holding_property to phoen_modify;

grant select on holding_property to phoen_read;

create table shareholder_group_shareholder
(
    id                   bigint generated by default as identity
        primary key,
    shareholder_group_id bigint not null
        constraint fk_shareholder_group_shareholder_shareholder_group
            references shareholder_group,
    shareholder_id       bigint not null
        constraint fk_shareholder_group_shareholder_shareholder
            references shareholder,
    created_by           varchar(255),
    created_ts           timestamp,
    last_changed_by      varchar(255),
    last_changed_ts      timestamp,
    constraint uniq_shareholder_group_shareholder_shareholder_group_id_shareho
        unique (shareholder_group_id, shareholder_id)
);

alter table shareholder_group_shareholder
    owner to "shareholder-register";

grant select, usage on sequence shareholder_group_shareholder_id_seq to phoen_modify;

grant select, usage on sequence shareholder_group_shareholder_id_seq to phoen_read;

create index shareholder_group_shareholder_shareholder_group_id_index
    on shareholder_group_shareholder (shareholder_group_id);

create index shareholder_group_shareholder_shareholder_id_index
    on shareholder_group_shareholder (shareholder_id);

grant delete, insert, select, update on shareholder_group_shareholder to phoen_modify;

grant select on shareholder_group_shareholder to phoen_read;

create table internal_shareholder_status_history
(
    id                   bigint generated by default as identity
        primary key,
    shareholder_id       bigint      not null
        constraint fk_internal_shareholder_status_history_shareholder
            references shareholder,
    status               varchar(64) not null,
    status_modified_date timestamp   not null
);

alter table internal_shareholder_status_history
    owner to "shareholder-register";

grant select, usage on sequence internal_shareholder_status_history_id_seq to phoen_modify;

grant select, usage on sequence internal_shareholder_status_history_id_seq to phoen_read;

create index internal_shareholder_status_history_shareholder_id_index
    on internal_shareholder_status_history (shareholder_id);

create index idx_internal_sh_status_shareholder_modified_desc
    on internal_shareholder_status_history (shareholder_id asc, status_modified_date desc, status desc);

grant delete, insert, select, update on internal_shareholder_status_history to phoen_modify;

grant select on internal_shareholder_status_history to phoen_read;

create table shareholder_subscription
(
    id                                 bigint generated by default as identity
        primary key,
    start_date                         timestamp,
    end_date                           timestamp,
    shareholder_id                     bigint not null
        constraint fk_shareholder_subscription_shareholder
            references shareholder,
    issuer_subscription_translation_id bigint not null
        constraint fk_shareholder_subscription_issuer_subscription_translation
            references issuer_subscription_translation
);

alter table shareholder_subscription
    owner to "shareholder-register";

grant select, usage on sequence shareholder_subscription_id_seq to phoen_modify;

grant select, usage on sequence shareholder_subscription_id_seq to phoen_read;

create index shareholder_subscription_shareholder_id_index
    on shareholder_subscription (shareholder_id);

create index shareholder_subscription_issuer_subscription_translation_id_ind
    on shareholder_subscription (issuer_subscription_translation_id);

grant delete, insert, select, update on shareholder_subscription to phoen_modify;

grant select on shareholder_subscription to phoen_read;

create index corporate_action_general_meeting_location_id_index
    on corporate_action (general_meeting_location_id);

create index corporate_action_corp_id_index
    on corporate_action (corp_id);

grant delete, insert, select, update on corporate_action to phoen_modify;

grant select on corporate_action to phoen_read;

create table corporate_action_aud
(
    id                          bigint   not null,
    corp_id                     varchar(255),
    record_date                 date,
    pay_date                    date,
    event_type                  varchar(255),
    instruction_deadline        timestamp,
    first_call                  timestamp,
    second_call                 timestamp,
    third_call                  timestamp,
    coupon                      integer,
    conversion_ratio            varchar(255),
    quantity                    varchar(255),
    status                      varchar(255),
    general_meeting_location_id bigint,
    rev                         integer  not null,
    revtype                     smallint not null,
    primary key (id, rev)
);

alter table corporate_action_aud
    owner to "shareholder-register";

grant delete, insert, select, update on corporate_action_aud to phoen_modify;

grant select on corporate_action_aud to phoen_read;

create table corporate_action_instrument
(
    id                  bigint generated by default as identity
        primary key,
    corporate_action_id bigint not null
        constraint fk_corporate_action_instrument_corporate_action_id
            references corporate_action,
    instrument_id       bigint not null
        constraint fk_corporate_action_instrument_instrument_id
            references instrument
);

alter table corporate_action_instrument
    owner to "shareholder-register";

grant select, usage on sequence corporate_action_instrument_id_seq to phoen_modify;

grant select, usage on sequence corporate_action_instrument_id_seq to phoen_read;

create index corporate_action_instrument_corporate_action_id_index
    on corporate_action_instrument (corporate_action_id);

create index corporate_action_instrument_instrument_id_index
    on corporate_action_instrument (instrument_id);

grant delete, insert, select, update on corporate_action_instrument to phoen_modify;

grant select on corporate_action_instrument to phoen_read;

create table corporate_action_instrument_aud
(
    id                  bigint   not null,
    corporate_action_id bigint,
    instrument_id       bigint,
    rev                 integer  not null,
    revtype             smallint not null,
    primary key (id, rev)
);

alter table corporate_action_instrument_aud
    owner to "shareholder-register";

grant delete, insert, select, update on corporate_action_instrument_aud to phoen_modify;

grant select on corporate_action_instrument_aud to phoen_read;

create table beneficial_owner
(
    id                                bigint generated by default as identity
        primary key,
    account_number                    varchar(255),
    account_operator_id               varchar(255)   not null,
    created_by                        varchar(255),
    created_ts                        timestamp,
    last_changed_by                   varchar(255),
    last_changed_ts                   timestamp,
    beneficial_owner_id               varchar(255)   not null,
    beneficial_owner_id_type          varchar(255),
    beneficial_owner_name             varchar(350),
    beneficial_owner_status           varchar(255),
    beneficial_owner_sur_name         varchar(255),
    beneficial_owner_transaction_type varchar(255),
    beneficial_owner_type             varchar(255),
    communication_id                  varchar(255),
    communication_id_cancel           varchar(255),
    corporate_action_event_id         varchar(255),
    date_of_production                date,
    dead_line                         date,
    multiple_records                  varchar(255),
    event_participation_methods       varchar(255),
    flux_progressive_number           varchar(255),
    holding_value                     numeric(18, 6) not null,
    instruction_type                  varchar(255),
    isin                              varchar(255)   not null,
    operation_type                    varchar(255),
    percentage_of_holding             numeric(5, 2),
    record_date                       date           not null,
    request_date                      date,
    address_city                      varchar(255),
    address_country                   varchar(255)   not null,
    address_line1                     varchar(255),
    address_line2                     varchar(255),
    address_postal_code               varchar(255),
    date_of_birth                     date,
    gender                            varchar(255),
    municipality_of_birth             varchar(255),
    nationality                       varchar(255),
    province_of_birth                 varchar(255),
    abi_guarantee                     varchar(255),
    pledge                            varchar(255),
    vote_rights                       varchar(255),
    processed                         boolean
);

alter table beneficial_owner
    owner to "shareholder-register";

grant select, usage on sequence beneficial_owner_id_seq to phoen_modify;

grant select, usage on sequence beneficial_owner_id_seq to phoen_read;

grant delete, insert, select, update on beneficial_owner to phoen_modify;

grant select on beneficial_owner to phoen_read;

create table permission
(
    id              bigint generated by default as identity
        constraint "PERMISSION_pkey"
            primary key,
    name            varchar(255) not null,
    created_by      varchar(255),
    created_ts      timestamp,
    last_changed_by varchar(255),
    last_changed_ts timestamp
);

alter table permission
    owner to "shareholder-register";

grant select, usage on sequence permission_id_seq to phoen_modify;

grant select, usage on sequence permission_id_seq to phoen_read;

grant delete, insert, select, update on permission to phoen_modify;

grant select on permission to phoen_read;

create table role
(
    id              bigint generated by default as identity
        constraint "ROLE_pkey"
            primary key,
    name            varchar(255) not null,
    created_by      varchar(255),
    created_ts      timestamp,
    last_changed_by varchar(255),
    last_changed_ts timestamp
);

alter table role
    owner to "shareholder-register";

grant select, usage on sequence role_id_seq to phoen_modify;

grant select, usage on sequence role_id_seq to phoen_read;

grant delete, insert, select, update on role to phoen_modify;

grant select on role to phoen_read;

create table role_permission
(
    id              bigint generated by default as identity
        constraint "ROLE_PERMISSION_pkey"
            primary key,
    permission_id   bigint not null
        constraint fk_role_permission_permission
            references permission,
    role_id         bigint not null
        constraint fk_role_permission_role
            references role,
    created_by      varchar(255),
    created_ts      timestamp,
    last_changed_by varchar(255),
    last_changed_ts timestamp
);

alter table role_permission
    owner to "shareholder-register";

grant select, usage on sequence role_permission_id_seq to phoen_modify;

grant select, usage on sequence role_permission_id_seq to phoen_read;

create index role_permission_permission_id_index
    on role_permission (permission_id);

create index role_permission_role_id_index
    on role_permission (role_id);

grant delete, insert, select, update on role_permission to phoen_modify;

grant select on role_permission to phoen_read;

create table shedlock
(
    name       varchar(64)  not null
        primary key,
    lock_until timestamp    not null,
    locked_at  timestamp    not null,
    locked_by  varchar(255) not null
);

alter table shedlock
    owner to "shareholder-register";

grant delete, insert, select, update on shedlock to phoen_modify;

grant select on shedlock to phoen_read;

create table error_log_assignee
(
    id              bigint generated by default as identity
        constraint "ERROR_LOG_ASSIGNEE_pkey"
            primary key,
    user_name       varchar(255) not null,
    error_log_id    bigint       not null
        constraint fk_error_log_assignee_error_log
            references error_log,
    created_by      varchar(255),
    created_ts      timestamp,
    last_changed_by varchar(255),
    last_changed_ts timestamp
);

alter table error_log_assignee
    owner to "shareholder-register";

grant select, usage on sequence error_log_assignee_id_seq to phoen_modify;

grant select, usage on sequence error_log_assignee_id_seq to phoen_read;

create index error_log_assignee_error_log_id_index
    on error_log_assignee (error_log_id);

grant delete, insert, select, update on error_log_assignee to phoen_modify;

grant select on error_log_assignee to phoen_read;

